language: rust

addons:
  apt:
    packages:
      - libssl-dev

os:
- linux
- osx

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
    - rust: nightly

script:
- cargo test -- --test-threads=1

after_success:
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
        bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        # Uncomment the following line for coveralls.io
        # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

        # Uncomment the following two lines create and upload a report for codecov.io
        cargo tarpaulin --out Xml -- --test-threads=1
        bash <(curl -s https://codecov.io/bash)
    fi
