[package]
name = "fts"
version = "0.1.0"
authors = ["dalance <dalance@gmail.com>"]
repository = "https://github.com/dalance/fts-rs"
license = "MIT"
readme = "README.md"
description = "Bindings for libc fts, and a library for high performance directory walking"
documentation = "http://dalance.github.io/fts-rs/fts-rs"

[dependencies]
bitflags       = "0.5.0"
enum_primitive = "0.1.0"
libc           = "0.2.8"
num            = "0.1.31"

[dev-dependencies]
walkdir        = "0.1.5"
